name: bot-cicd
run-name: ${{ github.actor }} push to master

on:
  push:
    branches:
      - master

jobs:
  base-infomations:
    runs-on: self-hosted
    steps:
      - name: Basic infomations
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  copy-rag:
    needs: base-infomations
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Copy repository code to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: './'
          target: /root/bot/sunck-bot
          rm: true
          tar_tmp_path: /root/bot/code_tmp
  
  run-rag:
    needs: [base-infomations, copy-rag]
    runs-on: self-hosted
    steps:
      - name: Stop
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/bot/sunck-bot/intelligent-robot/
            docker-compose stop
            docker-compose down
            docker rmi $(docker images --filter "label=maintainer=bot_system" -q) || true
      - name: Build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/bot/sunck-bot/intelligent-robot/
            docker-compose build
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/bot/sunck-bot/intelligent-robot/
            docker-compose up -d